# Python Function App to Linux on Azure
# Build a Python function app and deploy it to Azure as a Linux function app.
# Add steps that analyze code, save build artifacts, deploy, and more:

on:
  push:
    branches:
      - master

name: Build and deploy Python Function app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@master

    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_b0808e65-b07d-40 }}

    - name: 'Run pip'
      shell: bash
      working-directory: .
      run: |
        python -m pip install --upgrade pip
        python -m venv --copies worker_venv
        source worker_venv/bin/activate
        pip install -r requirements.txt

    # deploy web app using publish profile credentials
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      with:
        app-name: kuvfn
        package: app

    # Azure logout
    - name: logout
      run: |
        az logout